# Generated by Django 4.1.6 on 2023-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_project_resume_projectlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='behance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hackerank',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
