# Generated by Django 4.1.6 on 2023-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_resume_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
