# Generated by Django 4.1.6 on 2023-11-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_resume_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectlikes',
            name='Company_id',
        ),
        migrations.RemoveField(
            model_name='projectlikes',
            name='Project_id',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectLikes',
        ),
    ]
